name: CI CD Pipeline

on:
  push:
    branches: [main, release, dev*]
  pull_request:
    branches: [main, release, dev*]

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validação da mensagem de commit
        run: |
          echo "Validando mensagens de commit..."

          # Regex para validar a mensagem do commit
          REGEX="^((Merge.*)|(Revert.*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
        
          # Se a tag de base não existir, use o primeiro commit do repositório
          BASE_TAG=your-base-tag  # Substitua com o nome da sua tag de base
          if git rev-parse $BASE_TAG >/dev/null 2>&1; then
              COMMIT_RANGE=$BASE_TAG..HEAD
          else
              COMMIT_RANGE=$(git rev-list --max-parents=0 HEAD)
          fi
        
          # Loop para validar todas as mensagens de commit no intervalo
          for COMMIT_HASH in $(git rev-list --no-merges $COMMIT_RANGE); do
              MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)
              echo "Commit Message: ${MESSAGE}"
              if ! [[ "$MESSAGE" =~ $REGEX ]]; then
                  echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard."
                  exit 1
              else
                  echo "Valid commit message!"
              fi
          done
      - name: Instalação do JDK for x64
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

  build:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v4
      - name: Fase compilação do Maven
        run: mvn --batch-mode --update-snapshots compile

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Rodar testes unitários
        run: mvn --batch-mode --update-snapshots test
      - name: Jacoco push
        run: |
          git add -f ./target/site/jacoco/
          git status
          git commit -m "Jacoco Report"
          git push
